# These are supported funding model platforms
open_collective: creeperhub
patreon: giocolere # Replace with a single Patreon username
ko_fi: giocoliere # Replace with a single Ko-fi username
liberapay: creeperhub # Replace with a single Liberapay username
buy_me_a_coffee: creepercraft # Replace with a single Buy Me a Coffee username
custom: ["https://paypal.me/imgioco" ] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
